### ISSUE TITLE
Can't fetch mirrors

### ISSUE THREAD

**Issue by superDross** [vikstrous/pirate-get#100]
The mirror_list ('https://proxybay.co/list.txt') seems to be down as I keep receiving the follwoing error upon attempting to connect:

    Trying https://thepiratebay.org/... Failed 
    Could not fetch mirrors :(  
    [Errno 111] Connection refused

I've tried to find other existing lists and this site seems to be decent http://www.piratebayproxylist.co/. I have stored all the mirrors links from this webpage in a txt file named new_mirror_list.txt. I have gotten around this issue by doing the following command:

    pirate-get ubuntu -m `cat new_mirror_list.txt`

I was wondering if this can somehow be implemented in the code itself? Essentially replacing the mirror_list variable maybe?

**Comment by rnhmjoj** [comment]
Well yes, but it doesn't seem really useful to me. You can just set the mirrors in the config file yourself and save an extra http request.

**Comment by superDross** [comment]
I see, I was not aware I could set the mirrors in the config file. I'll do that now. Thank you!

**Comment by vikstrous** [comment]
Maybe we should just get rid of auto-discovering mirrors? It's slow and I suspect that tpb users who are in places where it's blocked already have a favourite mirror, so they can just configure it.

**Comment by arnauldb** [comment]
"Well yes, but it doesn't seem really useful to me. You can just set the mirrors in the config file yourself and save an extra http request."

and where is the config file ? thks

**Comment by superDross** [comment]
config file:
~/.config/pirate-get

**Comment by arnauldb** [comment]
thanks superDross, I installed from source and cannot find the config file...I followed your steps to add the mirrors list and it is workinfg fine, but I'd like to find the conf file. I have no conf file in my ./config directory.

**Comment by rnhmjoj** [comment]
@superDross https://github.com/vikstrous/pirate-get#configuration-file

**Comment by superDross** [comment]
@rnhmjoj
I sorted it out yesterday and came to realise this information was all available within the readme. Apologies, I'll make sure to take a look at the readme before raising an issue in the future. Thank you.

**Comment by superDross** [comment]
@arnauldb

Default is $XDG_CONFIG_HOME/pirate-get

You should also check out the readme file. Naturally it contains a lot of useful information:

https://github.com/vikstrous/pirate-get/blob/master/README.md

**Comment by arnauldb** [comment]
sorry for the late reply, I figured it out. Thanks rnhmjoj  &  superDross.
