### ISSUE TITLE
transmission  with authentication

### ISSUE THREAD

**Issue by danradom** [vikstrous/pirate-get#103]
I've been trying unsuccessfully to get pirate-get to open magnets with transmission-remote using authentication with transmission.  Does this work and can someone tell me the formatting of the openCommand?

**Comment by rnhmjoj** [comment]
pirate-get, when running with the `--transmission` option, simply calls `transmission-remote --add [url,]`. I have never used authentication but I suppose you do `--auth user:pass`, so your openCommand should be
```
transmission-remote --auth user:pass --add %s
```

**Comment by danradom** [comment]
Thanks.  This is what I had tried earlier.  My issue was that I needed to set transmission = false in my config file to get it to use the openCommand.
