### ISSUE TITLE
Color Problem

### ISSUE THREAD

**Issue by opensamba** [vikstrous/pirate-get#107]
Hi, 
I like the color option for pirate-get, but the blue color is very bad for my dark terminal

So I tried tu disable color in the config file ~/.config/pirate-get

```
; use colored output
colors = False
```
but with my surprise nothing changed, checking the code I see the color settings works only if is passed by the command line (which is bad).

So I tried to change the color in the code, but also this is very bad. 

Can you tell me which is the best way to get a better color or disable it?

**Comment by rnhmjoj** [comment]
Yes, this issue was recently [fixed](https://github.com/vikstrous/pirate-get/commit/c04b7ec0d15c6072da1c11a14a75d5c7d6947fe9) but not yet released.
You can use `pirate-get --disable-colors` in the meantime.

**Comment by opensamba** [comment]
thanks for the info.

What about if I want to change the color to something dark-friendly ?

**Comment by rnhmjoj** [comment]
The colors we use are the 16 ANSI colors, you can see [here](https://github.com/vikstrous/pirate-get/blob/master/pirate/print.py#L22) which. The output depends on the terminal and palette you are currently using. They are not configurable from pirate-get but you may change the look of your palette if the blue is particularly bad.

**Comment by rnhmjoj** [comment]
@vikstrous Can you upload v0.2.11 to PyPI?

**Comment by vikstrous** [comment]
Yep. Sorry for the delay. I didn't want to release a new version with only one commit, but at the current rate of development, it makes sense to just do it.

**Comment by vikstrous** [comment]
New version released and tested.
