### ISSUE TITLE
Support for transmission host if deamon is not local

### ISSUE THREAD

**Issue by bignellrp** [vikstrous/pirate-get#127]
transmission-remote supports adding host but this does not seem to be an option on pirate-get

e.g. 

transmission-remote 192.168.0.5 -p 9091 -n username:password -a file.torrent

Could it be an option in the .config/pirate-get

transmission = true
; set to the ip of the transmission host if not local
transmission-host = 192.168.0.5
; set to username:password if needed
transmission-auth = username:password
; set to the port number if needed
transmission-port = 9091

e.g.

config.set('Misc', 'transmission-host', '')

parser.add_argument('-H', '--host', dest='host',
                        help='transmission-remote rpc host. default is localhost')

if args.port:
        args.transmission_command.append(args.host)
    elif config.get('Misc', 'transmission-host'):
        args.transmission_command.append(config.get('Misc', 'transmission-host'))

**Comment by bignellrp** [comment]
Update:

I just tried this on my local version by manually editing pirate.py with the config above but this only works with the port commented as i think it needs a colon between the host and the port.  My python knowledge is limited so I'm not sure how to do this as an if.

e.g if host and port is specified then add host : port, else add host or port without the colon.

**Comment by rnhmjoj** [comment]
It shouldn't be too difficult to add. Actually I'd change the `port` argument to be `address:port` instead. I'm now working on other things but I could give it a try in a couple of days.
