### ISSUE TITLE
Crash on mirror with fake search results table

### ISSUE THREAD

**Issue by bignellrp** [vikstrous/pirate-get#129]
Hi,

Not sure if a recent python upgrade has caused this but getting the following python traceback error now.

Traceback (most recent call last):
  File "/usr/local/bin/pirate-get", line 11, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.6/site-packages/pirate/pirate.py", line 453, in main
    pirate_main(args)
  File "/home/username/.local/lib/python3.6/site-packages/pirate/pirate.py", line 353, in pirate_main
    results, site = search_mirrors(printer, args)
  File "/home/username/.local/lib/python3.6/site-packages/pirate/pirate.py", line 280, in search_mirrors
    result = connect_mirror(mirror, printer, args)
  File "/home/username/.local/lib/python3.6/site-packages/pirate/pirate.py", line 268, in connect_mirror
    mirror=mirror)
  File "/home/username/.local/lib/python3.6/site-packages/pirate/torrent.py", line 151, in remote
    res_l += parse_page(res)
  File "/home/username/.local/lib/python3.6/site-packages/pirate/torrent.py", line 110, in parse_page
    tag['href'].startswith('magnet'))['href']
TypeError: 'NoneType' object is not subscriptable

python3 --version     
Python 3.6.8

**Comment by rnhmjoj** [comment]
Which mirror did pirate-get select when it crashed?

**Comment by bignellrp** [comment]
Trying https://proxybay.pro... Traceback (most recent call last)

or

Trying https://piratebay-proxy.net... Failed 
Trying https://piratepiratepirate.net... Failed 
Trying https://ukpiratebayproxy.com... Failed 
Trying https://thepiratebayproxy.info... Traceback (most recent call last):

**Comment by rnhmjoj** [comment]
Ok, there is an ad that's breaking an assumption in the scraper.
As a workaround you can choose a different mirror with `-m` or by setting `mirror =` in the pirate-get config file.

**Comment by bignellrp** [comment]
Thanks. I really appreciate the time spent so far and the fast replies but unfortunately none of the mirrors I try are working. Is there anyway to code around the ad or at least gracefully fail and move on to the next mirror?

Here is the list I’ve tried:

mirror = https://proxybay.pro https://piratebay-proxy.net https://piratepiratepirate.net https://ukpiratebayproxy.com https://thepiratebayproxy.info https://thepiratebay.guru https://thepiratebaybay.org https://proxytpb.net https://proxyofthepiratebay.com https://proxybay.site https://piratebayproxy.cx https://pirateaccess.info https://openpiratebay.eu https://lepiratebay.org https://freepirate.net https://proxybay.center https://thepiratebay.tokyo https://thepiratebay11.org https://pirateunblocker.net

**Comment by rnhmjoj** [comment]
Uhm, so it's not limited to one site... I'll have to fix it sooner before all proxies become unusable.
Anyway, try this: https://pirateproxy.onl it works for me. Also if have tor you could try to use http://uj3wazyk5u4hnvtk.onion.

**Comment by bignellrp** [comment]
That first one works. Thanks.

**Comment by rnhmjoj** [comment]
I fixed the crash and made the scraping more reliable in https://github.com/vikstrous/pirate-get/commit/6642130fc554678229d24c5e64dfdabf7e52ae53.

**Comment by rnhmjoj** [comment]
@vikstrous can you upload the release on pypi?

**Comment by vikstrous** [comment]
Yep. Doing it now!

**Comment by vikstrous2** [comment]
Done, but for some reason I can't pip install it even though it shows up on the website. Can you confirm if it's working?

**Comment by vikstrous** [comment]
Done, but for some reason I can't pip install it even though it shows up on the website. Can you confirm if it's working?

**Comment by bignellrp** [comment]
Yes, this is working now.  Thanks guys.

pip3 install pirate-get

Successfully installed beautifulsoup4-4.8.1 colorama-0.4.1 pirate-get-0.3.4 pyperclip-1.7.0 soupsieve-1.9.5 termcolor-1.1.0 veryprettytable-0.8.1

Trying https://proxybay.pro... Ok 
 LINK  SEED  LEECH  RATIO       SIZE  UPLOAD       NAME  
blah blah blah
