### ISSUE TITLE
Mirrors all offline, should be able to specify target mirror URLs in config

### ISSUE THREAD

**Issue by RightMakesMight** [vikstrous/pirate-get#131]
All of the piratebay mirrors that pirate-get searches by default are offline, and there isn't an immediately obvious means to specify other mirrors to search, of which there are many. Does such a method of alternate mirror specification exist?

If it does not, then I would suggest adding one, as piratebay mirrors are being continually created and taken down, any static list will be rendered unusable sooner or later.

**Comment by rnhmjoj** [comment]
The mirrors are taken from the proxy bay and updated continuously: https://proxybay.uno/list.txt. Notheless, many may or may not work depending on your country. This url can't be changed but you can provide your own list using the argument
```
 -m MIRROR [MIRROR ...], --mirror MIRROR [MIRROR ...]
                        the pirate bay mirror(s) to use

```

or the `mirror` [configuration](https://github.com/vikstrous/pirate-get#default-config-file) option.

**Comment by RightMakesMight** [comment]
Thanks. I've attempted to use the argument you suggest, all of my provided urls give the error (Mirror does not contain magnets.), while all of the default urls result in (HTTP Error 503: Service Temporarily Unavailable) or (HTTP Error 404: Not Found), though the links work when I navigate to them myself.

**Comment by rnhmjoj** [comment]
> Mirror does not contain magnets.

There are mirrors that don't contain any magnet links: they are effectively useless. They have been [blacklisted](https://github.com/vikstrous/pirate-get/blob/master/pirate/data/blacklist.json) but new ones pop up from time to time.

**Comment by icherfas** [comment]
hi,
I have tried to add the site: https://thepirate-bay.org
but I get "(Blocked mirror detected.)"
all other sites are also failing.
what can I do?

Thanks in advance!

**Comment by rnhmjoj** [comment]
I'll look into the 404 as soon as I have some spare time. I guess there has been some change to the structure of the page that's making the parser fail.

> Blocked mirror detected

That's usually means the mirror is either: blocked by your ISP, having some stupid DoS projection that requires JS or a scam.

**Comment by rnhmjoj** [comment]
Apparently they added some kind cookie based of DoS protection. If you reload the page a couple times in a browser you should get the 403 error page as well.

We need to store and subsequently use in each request a cookie that's sent on the first request, before a redirect.

**Comment by eyalzek** [comment]
Still seeing the same behavior with 0.3.5:
```
$ pirate-get
Trying https://thepiratebay.org/... Failed  (The read operation timed out)
Trying https://pirateproxy.page... Failed  (HTTP Error 503: Service Temporarily Unavailable)
Trying https://tpb14.ukpass.co... Failed  (HTTP Error 503: Service Temporarily Unavailable)
Trying https://knaben.xyz/ThePirateBay.php... Failed  (HTTP Error 404: Not Found)
Trying https://piratesbaycc.com... Failed  (HTTP Error 404: Not Found)
Trying https://thepiratebay.vip... Failed  (HTTP Error 403: Forbidden)
No more available mirrors :(  
$ pirate-get --version
pirate-get, version 0.3.5
```

**Comment by rnhmjoj** [comment]
All right, here a summing up:

* https://thepiratebay.org/ is really timing out, not an issue of pirate-get

* The 503 errors are cloudflare DDoS protection: the only thing I can do is blacklist them.

* https://knaben.xyz/ThePirateBay.php is a not ever a tpb mirror: it has not `top/all` and `search` and such. It should be blacklisted as well. Same for https://piratesbaycc.com, no `search` page.

* I can't reproduce the 403 with https://thepiratebay.vip

I no mirror is working your best bet is the hidden service, provided you have tor running:  http://piratebayztemzmv.onion

I'll blacklist the relevant mirror soon.

**Comment by rnhmjoj** [comment]
I updated the blacklist and added an ad-hoc message for cloudflare.

**Comment by vikstrous** [comment]
Thanks. I'll do another release I guess.

**Comment by rnhmjoj** [comment]
Thank you.
