### ISSUE TITLE
Script exits with error: Exception: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by tedmunga** [vikstrous/pirate-get#135]
pirate-get errors when trying to copy to clipboard or displaying information.

elect links (Type 'h' for more options, 'q' to quit): h

Options:
<links>: Download selected torrents
[m<links>]: Save magnets as files
[c<links>]: Copy magnets to clipboard
[t<links>]: Save .torrent files
[d<links>]: Get descriptions
[f<links>]: Get files
[p] Print search results
[q] Quit

Select links (Type 'h' for more options, 'q' to quit): c0

Exception: 'NoneType' object has no attribute 'group' 

I am on Ubuntu 20.04
$ python
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux

**Comment by rnhmjoj** [comment]
Thank you, I have never noticied this before. There was a problem with a regex that matched the magnet info hash: I should have fixed it with  f115bfd8d3435496474ce0111e0ce909b4e049da.

**Comment by rnhmjoj** [comment]
@vikstrous can you upload v0.3.7 to pypi?

**Comment by vikstrous** [comment]
0.3.7 released

**Comment by rnhmjoj** [comment]
Thank you!

**Comment by tedmunga** [comment]
It looks like the clipboard has been fixed but options
m<link>
t<link>
d<link>

all exit with this error.
Exception: 'NoneType' object has no attribute 'group'

**Comment by rnhmjoj** [comment]
It's more 404s. It looks like the pirate bay has completely changed their interface.
Now they only serve a JS that's doing some requests to a JSON api at https://apibay.org.
It should be a lot easier to deal with than parsing html but pirate-get should be rewritten.

**Comment by tedmunga** [comment]
do you think a rewrite is likely to happen?

**Comment by rnhmjoj** [comment]
It is happening, see #136. I started working on this yesterday and it's already pretty good.
If you want to try it out I can give you directions: it could use some more testing.

**Comment by rnhmjoj** [comment]
It is happening, see #136. I started working on this yesterday and it's already pretty good.
If you want to try it out I can give you directions: it could use some more testing.

**Comment by tedmunga** [comment]
I'd love to test it. how can I get a copy of the new one?

**Comment by rnhmjoj** [comment]
If you know git, clone the repository and switch to the `api` branch; otherwise download this [archive](https://github.com/vikstrous/pirate-get/archive/api.zip) and extract it.

If you have pirate-get installed in your system, you should already have all the dependency needed so try running
```
python -m pirate.pirate <options>
```
this is the equivalent of `pirate-get <options>`.

Also, If you'd like to install the new version try
```
pip install .
```

**Comment by rnhmjoj** [comment]
Fixed in v0.4.0.

**Comment by tedmunga** [comment]
Excellent thank you :)
