### ISSUE TITLE
Timeout failures

### ISSUE THREAD

**Issue by bobafett2010** [vikstrous/pirate-get#141]
I tried to use pirate-get today and I was encountered with a bunch of errors. I updated the machine and uninstalled/reinstalled pirate-get with pip and I am still encountering the problems.

Not sure if I am the only one encountering this. 

[Screenshot included]

![image](https://user-images.githubusercontent.com/51348658/97467795-ef537400-191a-11eb-9abb-6304936ce86a.png)

**Comment by rnhmjoj** [comment]
The mirrors you listed seems ok from here. It could be your network is too slow for the default timeout: try increasing it with `--timeout 10` and see if still fails.

**Comment by bobafett2010** [comment]
Yeah for some reason it works again now. I tried it on multiple different devices on different networks and it had the same issues but now it works when I checked it a few hours later.

**Comment by rnhmjoj** [comment]
I'm closing since this is not an issue in pirate-get itself.
