### ISSUE TITLE
Why license this project under agpl instead of just gpl?

### ISSUE THREAD

**Issue by Scottpedia** [vikstrous/pirate-get#142]
Just out of curiosity, why did you license thisb project under agpl instead of gpl while this program is supposed to run on the client side?

**Comment by rnhmjoj** [comment]
ping @vikstrous

**Comment by vikstrous** [comment]
No particular reason. I don't think there's a difference in this case unless someone uses the code to build a web service.

**Comment by Scottpedia** [comment]
OK thanks for the answer! Closing...
