### ISSUE TITLE
Req: can you add fetch_details?

### ISSUE THREAD

**Issue by rushic24** [vikstrous/pirate-get#144]
details like: 
![image](https://user-images.githubusercontent.com/6279035/133184204-834322cf-2f22-4cc6-b345-cb72e269f6d3.png)

**Comment by rnhmjoj** [comment]
This should be the torrent description.
Just type `dn` where `n` is the search result number of which you want to see the details.

**Comment by rushic24** [comment]
Cool thanks!.
