### ISSUE TITLE
Publish to package managers

### ISSUE THREAD

**Issue by defektive** [vikstrous/pirate-get#24]
it would awesome if we could

```bash

# use apt-get
apt-get install pirate-get

# apt-get's osx cousin
brew install pirate-get
```

related links
https://github.com/Homebrew/homebrew/wiki/Formula-Cookbook
https://help.launchpad.net/Packaging/PPA
https://wiki.archlinux.org/index.php/creating_packages

**Comment by vikstrous** [comment]
Published to pip.

**Comment by rnhmjoj** [comment]
Strange: there's no download button or tarball on the pypi [page](https://pypi.python.org/pypi/pirate-get/0.2.5).

**Comment by vikstrous** [comment]
After `./setup.py register` I had to run `./setup.py register sdist upload`. Thanks for pointing this out.

**Comment by rnhmjoj** [comment]
The [nix package](https://github.com/NixOS/nixpkgs/pull/9574) of pirate-get has been accepted.

**Comment by vikstrous** [comment]
I think pypi is the only important one for now.
