### ISSUE TITLE
local database errors

### ISSUE THREAD

**Issue by gotbletu** [vikstrous/pirate-get#27]
$ pirate-get --local "poor3.xml" archlinux

Traceback (most recent call last):
  File "/usr/bin/pirate-get", line 310, in <module>
    main()
  File "/usr/bin/pirate-get", line 208, in main
    mags = local(args)
  File "/usr/bin/pirate-get", line 193, in local
    htmlparser = MyHTMLParser(args.q)
AttributeError: 'Namespace' object has no attribute 'q'

**Comment by rnhmjoj** [comment]
There have been lots of changes. Now the local db option should works.
Tell me if you find other issues.

**Comment by vikstrous** [comment]
Since TPB team has not published any new versions of their database I think we should kill this feature completely. Any objections?

**Comment by rnhmjoj** [comment]
Yes, It's also pretty limited (only names and magnets) but it's better than nothing when tpb is down. I would keep it.

**Comment by rnhmjoj** [comment]
I close this since it's working now.
