### ISSUE TITLE
sudo pirate-get update

### ISSUE THREAD

**Issue by vikstrous** [vikstrous/pirate-get#30]
Create an update mechanism that just fetches and installs the latest version of the code from the github repo.

**Comment by Rnhmjoj** [comment]
I think it would be better to make it a pipit package so that it can be easily installed and updated via pip.
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by vikstrous** [comment]
I agree. That's a nice guide. I created an account. My username is `vikstrous`. If you make the package try to add me as a second maintainer. Otherwise, I'll give it a shot later on myself and I'll add you when you have an account.

**Comment by rnhmjoj** [comment]
I have created a new branch `pypi` with a packaged version of pirate-get.
It's likely that I have broken a few things even if I did some static analysis, we really needs tests.
However can you give it a try and see if you can build/upload it to the pypi?

**Comment by vikstrous** [comment]
Thanks! It seems to work for my primary use case - a simple search and opening the torrent with transmission. I uploaded it to pypi. I won't update the AUR for now, but I think I might remove the AUR package because we don't really need it if we have the pypi one. There's a lot more refactoring and testing left to do, but this is big step in the right direction.
