### ISSUE TITLE
Only one magnet link file is created when downloading multiple magnet links to files

### ISSUE THREAD

**Issue by murrayf** [vikstrous/pirate-get#32]
Hi,

  I'm trying to download several torrents from pirate-get results, but it only accepts the first one and I have to restart program. Could you please tell me how the command is for, for example download "1", "5" and "15" respective torrents?

**Comment by Rnhmjoj** [comment]
Ok, it's done. In the last commit the option to save magnet links will write each magnet in a different file with the name of the torrent.

**Comment by murrayf** [comment]
thanks.

-----------------
Alberto Segura.
