### ISSUE TITLE
Torrent rather than magnet

### ISSUE THREAD

**Issue by bignellrp** [vikstrous/pirate-get#41]
Thanks for getting this working with oldpiratebay, it works well.

Is there an option to download the torrent file rather than the magnet link?  Otherwise i have to convert the magnet link to get it to work with rtorrent.

**Comment by vikstrous** [comment]
So, I actually just realized that the open bay actually does have torrent files in addition to the magnet links. This is definitely something we can do.

**Comment by bignellrp** [comment]
Thanks.  That would be proper handy if it could use torrent files.  I tried swapping to Deluge rather than using rtorrent so it supports magnet but i don't like the Deluge console interface.

**Comment by vikstrous** [comment]
Now that we are using the pirate bay, the right way to do this would be http://torcache.net/

**Comment by Rnhmjoj** [comment]
It should be easy to implement. However I have really no free time this week.
Maybe this weekend I will try.

**Comment by Rnhmjoj** [comment]
I found a few hours tonight. I implemented the download of torrents cached by http://torcache.net
It should work. I tried it on a several torrents in the top list: most of them are cached.

**Comment by vikstrous** [comment]
Nice! I think this needs to be updated too though: https://github.com/vikstrous/pirate-get/blob/4ced152b9c56088f0a80c77a9a3434b1d9ca9bfd/pirate-get.py#L579

**Comment by Rnhmjoj** [comment]
I have changed the save to file system.
Now there are 3 different option that you can set via arguments of config file.
I have tested a bit all the options and everything seems to work but it's highly possible that there are bugs because I made a lot of changes.

**Comment by vikstrous** [comment]
The changes look good, but I can't test them right now because the pirate bay is down again.

**Comment by vikstrous** [comment]
I found just one issue. I think we should make the default destination the current directory because there's no way to set it from the command line.

**Comment by rnhmjoj** [comment]
Ok, I made the change: as the other options you can override the config with the command line arguments. If both the config and the argument are none the current working directory will be used.

**Comment by rnhmjoj** [comment]
I forgot about that part. It uses the working directory anyway but it's better to change that.
Thanks.

**Comment by bignellrp** [comment]
Thanks for all your hard work.  Just did a clone to install the latest version but now getting this error:

  File "/usr/bin/pirate-get", line 149
    def print(*args, **kwargs):
            ^
SyntaxError: invalid syntax

**Comment by rnhmjoj** [comment]
Are you using python 2? I ported pirate-get to python 3 so it has become incompatible.
You need python 3 now.

**Comment by bignellrp** [comment]
I've installed python3 (by Ubuntu version is 12.04 so 2.7 is default) but i still get the error.

**Comment by vikstrous** [comment]
The default version of python on Ubuntu is probably 2 and the #! uses just "python". The install script tries to detect the presence of python3. If you install it with the install script or change the #! on the first line it should work.

On March 28, 2015 12:04:34 PM EDT, Richard Bignell <notifications@github.com> wrote:
>I've installed python3 (by Ubuntu version is 12.04 so 2.7 is default)
>but i still get the error.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/issues/41#issuecomment-87255381

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vikstrous** [comment]
AFAIK this works now. Feel free to create a new issue if something related to this breaks.
