### ISSUE TITLE
It's broken again

### ISSUE THREAD

**Issue by vikstrous** [vikstrous/pirate-get#43]
They removed the sorting feature from oldpiratebay.org. I don't know why or how long it will be like this, but it might make sense to go back to using thepiratebay.se. The long term solution is to use more than one source, but that will take more effort.

**Comment by Rnhmjoj** [comment]
I made a fork some months ago with slightly variations.
It is still using piratebay.se and works quite well though there are timeout problems sometimes.
If you want to take a look: https://github.com/Rnhmjoj/pirate-get

**Comment by vikstrous** [comment]
Looks great! I'll use this as the official version and I'll add you as a contributor on this repo.

**Comment by vikstrous** [comment]
Why did you change the installation path to `/usr/local/bin` from `/usr/bin` ? On arch linux this doesn't seem to be part of my path. I'm planning to change it back, but I wanted to check with you first.

**Comment by vikstrous** [comment]
I pushed your branch with a few fixes to master. Check if it still works for you and I'll publish it in the AUR.

**Comment by Rnhmjoj** [comment]
On OS X (with homebrew) you mostly use `/usr/local/bin` since `/usr/local` is not owned by root.
However it's fine, no problem: I'm happy you like it ;)

**Comment by Rnhmjoj** [comment]
I close this one since it's working again.
