### ISSUE TITLE
fix potential command execution vulnerability with transmission mode (-t)

### ISSUE THREAD

**Issue by vikstrous** [vikstrous/pirate-get#45]
A malicious pirate bay mirror can attack a pirate-get user who uses transmission mode (-t) by serving malicious results https://github.com/vikstrous/pirate-get/blob/master/pirate-get.py#L671

**Comment by rnhmjoj** [comment]
Right. One can do something like this:
```
>>> a = "[urlhere]\"; echo dobadthings; echo \""
>>> subprocess.call('echo this is a url "%s"' % a, shell=True)
this is a url [urlhere]
dobadthings
```
The magnet url has to be validated. We can probably reuse the regex you used to extract it from the piratebay page.
