### ISSUE TITLE
---custom fails when `%s` is quoted

### ISSUE THREAD

**Issue by vikstrous** [vikstrous/pirate-get#49]
follow up from #48

From #48:

I'm currently travelling, so it might take me some time before I get to fixing it. If anyone wants to give it a shot, I recommend just stripping the quotation marks around any of the items in the ret array.

**Comment by rnhmjoj** [comment]
I tried `pirate-get --custom "echo '%s'"`. This is working.

**Comment by vikstrous** [comment]
Yeah. The issue is that it prints the quotes.
