### ISSUE TITLE
Error parsing config

### ISSUE THREAD

**Issue by haggardsford** [vikstrous/pirate-get#51]
Traceback (most recent call last):                                                  
                                                                                     │  File "/usr/bin/pirate-get", line 696, in <module>                                 
                                                                                     │    main()                                                                          
                                                                                     │  File "/usr/bin/pirate-get", line 685, in main                                     
                                                                                     │    elif args.command or config.get('Misc', 'openCommand'):                         
                                                                                     │  File "/usr/lib/python3.4/configparser.py", line 773, in get                       
                                                                                     │    d)                                                                              
                                                                                     │  File "/usr/lib/python3.4/configparser.py", line 374, in before_get                
                                                                                     │    self._interpolate_some(parser, option, L, value, section, defaults, 1)          
                                                                                     │  File "/usr/lib/python3.4/configparser.py", line 423, in _interpolate_some         
                                                                                     │    "found: %r" % (rest,))                                                          
                                                                                     │configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%
                                                                                     │s                       ; specify a custom command for opening the magnet'

**Comment by vikstrous** [comment]
Can you post your config?

**Comment by haggardsford** [comment]
@ work ATM, but I just copied default from the readme into ~/.config/pirate-get, the above error was after I had removed: transmission = false and colors = true, which resulted in ValueErrors. I'll post outputs when I get home later

**Comment by rnhmjoj** [comment]
The config in the readme is an explanation of what the options are and what they do: one is not supposed to paste it as is. It's not valid for the parser. The config file is generated when you start pirate-get the first time so you don't even need to create it. Perhaps I should have written it more clear.

Anyway I think the error is that the INI parser (ConfigParser) only accepts as comments lines that begin with a colon.

**Comment by haggardsford** [comment]
haha, well don't I feel stupid. Thanks for the info.

**Comment by rnhmjoj** [comment]
No problem.

**Comment by rnhmjoj** [comment]
I updated the readme. The config now is valid for the parser.

**Comment by jangrewe** [comment]
I have the same error message, copied the config from the README and only adjusted the "openCommand".
It works if i give that openCommand as a parameter, but not in the config.

```
openCommand = "/usr/bin/deluge-console -c /etc/deluge add '%s'"
```
I've tested with quotes, double quotes, no quotes... always the InterpolationSyntaxError.

**Comment by jangrewe** [comment]
Okay, this works for me:

```
openCommand = /usr/bin/deluge-console -c /etc/deluge add %%s
```

**Comment by vikstrous** [comment]
Oh, weird. It sounds like the config parser interprets percents signs as environment variables. http://stackoverflow.com/questions/14340366/configparser-and-string-with
I'll change it to use RawConfigParser

**Comment by rnhmjoj** [comment]
I think we should keep environment variables substitution. We should change the sequence that represent the magnet instead, with something less ambiguous.

**Comment by vikstrous** [comment]
Hmm.. I think we should do both. Do you think the environment variables thing is actually useful?

On November 4, 2015 11:14:50 PM PST, Michele Guerini Rocco <notifications@github.com> wrote:
>I think we should keep environment variables substitution. We should
>change the sequence that represent the magnet instead, with something
>less ambiguous.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/issues/51#issuecomment-153975376

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rnhmjoj** [comment]
Personally I never used it but it can always come handy, isnt't?
