### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by BueHiwzr** [vikstrous/pirate-get#53]
In OSX 10.9.5, will throw an urllib.error.URLError

<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>

This seems to be a problem of urllib.request.

The following code will throw the same error

```
def main():
	req = request.Request('https://proxybay.co/list.txt', headers=default_headers)
	f = request.urlopen(req, timeout=default_timeout)
```

**Comment by vikstrous** [comment]
Proxybay is behind cloudflare and does not support sslv3. I don't understand why your python would be trying to use sslv3 at all. Can you try installing python from brew?

**Comment by BueHiwzr** [comment]
I did install python from brew but I have the same result.

Could this be because of the problem mentioned here? : http://anotherlayer.net/2014/10/16/forcing-tls1-in-pythons-urllib2-on-osx/

**Comment by BueHiwzr** [comment]
I've found the issue. Python 3.4 wasn't linked :)
