### ISSUE TITLE
Front slash in torrent name treated as file path

### ISSUE THREAD

**Issue by zigzulu** [vikstrous/pirate-get#73]
Attempting to download a torrent file with a name including a front slash into a local directory throws a "FileNotFoundError"

**Comment by vikstrous** [comment]
Makes sense. That code path is pretty hacky. We need to sanitize the torrent names. Would it make sense to replace `\` and `/` with `_`?

**Comment by rnhmjoj** [comment]
Why would the filename even contain such a character? It is [forbidden](http://stackoverflow.com/questions/9847288/is-it-possible-to-use-in-a-filename) on every *nix system and it [seems](http://stackoverflow.com/questions/10708334/how-can-i-create-files-on-windows-with-embedded-slashes-using-python) to be the same even for windows.

**Comment by vikstrous** [comment]
It's not a filename. We are using it to name our files, but it's just the name of the torrent. The server can provide anything.

**Comment by rnhmjoj** [comment]
Ah, makes sense.
