### ISSUE TITLE
SyntaxError: invalid syntax on Mac

### ISSUE THREAD

**Issue by breerly** [vikstrous/pirate-get#78]
After fresh `sudo pip install pirate-get`, I'm unable to run the program:

```
~ » pirate-get -h
Traceback (most recent call last):
  File "/usr/local/bin/pirate-get", line 9, in <module>
    load_entry_point('pirate-get==0.2.8', 'console_scripts', 'pirate-get')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 519, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2310, in load
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2316, in resolve
  File "/usr/local/lib/python2.7/site-packages/pirate/pirate.py", line 20
    from pirate.print import Printer
                    ^
SyntaxError: invalid syntax
```

**Comment by vikstrous** [comment]
What version of python 3 do you have?

On January 2, 2016 2:31:13 AM EST, Grayson Koonce <notifications@github.com> wrote:
>After fresh `sudo pip install pirate-get`, I'm unable to run the
>program:
>
>```
>~ » pirate-get -h
>Traceback (most recent call last):
>  File "/usr/local/bin/pirate-get", line 9, in <module>
>load_entry_point('pirate-get==0.2.8', 'console_scripts',
>'pirate-get')()
>File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py",
>line 519, in load_entry_point
>File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py",
>line 2630, in load_entry_point
>File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py",
>line 2310, in load
>File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py",
>line 2316, in resolve
>File "/usr/local/lib/python2.7/site-packages/pirate/pirate.py", line 20
>    from pirate.print import Printer
>                    ^
>SyntaxError: invalid syntax
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/issues/78

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by breerly** [comment]
Aaaaand I installed with python2 :P

**Comment by vikstrous** [comment]
I'm surprised it let you. Do we not specify in pip that it works only on 3?

On January 2, 2016 2:51:41 AM EST, Grayson Koonce <notifications@github.com> wrote:
>Aaaaand I installed with python2 :P
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/issues/78#issuecomment-168372416

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rnhmjoj** [comment]
It's tagged as `Programming Language :: Python :: 3 :: Only` but probably this as no effect.

**Comment by breerly** [comment]
Suggest putting a check in setup.py and raising an exception if not greater than 3.wtvr, this will save people time.

**Comment by vikstrous** [comment]
https://github.com/vikstrous/pirate-get/pull/79

**Comment by breerly** [comment]
Cool, thanks @vikstrous
