### ISSUE TITLE
system can't find pirate-get

### ISSUE THREAD

**Issue by cesarpachon** [vikstrous/pirate-get#93]
hi! python's noob question.. I installed pirate-get successfully: 
pip3 list | grep pirate-get
pirate-get (0.2.8)
but if I try to execute it, it says "pirate-get: command not found"
in what other way can I launch the program? maybe some argument to python executable? 
thanks! (ubuntu 16, phython 3.4.3+)

**Comment by rnhmjoj** [comment]
Strange, maybe you are some entry in the `PATH`.
You could try to run it by loading `main()` in a REPL:
```
from pirate.porate import main
main()
```

**Comment by cesarpachon** [comment]
no look.. I discovered that the file was installed in ~/.local/bin, running from that dir works without any issue. thanks!

**Comment by vikstrous** [comment]
What distro are you using? This sounds very strange.

**Comment by cesarpachon** [comment]
distro info:
Ubuntu 15.04 wily 
Linux pc-ubuntu 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cesarpachon** [comment]
I used 'pip3 install pirate-get' (no sudo, I think). the command doesn't looks like an alias:
which pip3
/usr/bin/pip3
maybe this is also relevant:
:~ : which pip
/usr/bin/pip
:~ : pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
:~ : pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

**Comment by morhook** [comment]
Same thing happened on Ubuntu 18.04. Installed pip3 with 

    sudo apt install python3-pip

(and used already installed python3 3.6.9)
