### ISSUE TITLE
default flag -T not clearly documented

### ISSUE THREAD

**Issue by BardiaAfshin** [vikstrous/pirate-get#95]
When using the option to download the .torrent file as so

```shell
pirate-get -T 'ubuntu-1206'
```

Here's a dump of the trace
```trace
Saving selected torrents...
Traceback (most recent call last):
  File "/usr/local/bin/pirate-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 396, in main
    pirate_main(args)
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 377, in pirate_main
    pirate.torrent.save_torrents(choices, results, args.save_directory)
TypeError: save_torrents() missing 1 required positional argument: 'folder'
```

Also, where is the log file on the mac?

**Comment by rnhmjoj** [comment]
Thank you. This is a bug.
@vikstrous the first argument of `save_torrents` should be `printer`.

Anyway `-T` will save the torrents in the save-directory, which defaults to the current directory if not set.
You use `-S` or `Save.directory` in the config to change that.
