### ISSUE TITLE
Using pipes in openCommand

### ISSUE THREAD

**Issue by mrzool** [vikstrous/pirate-get#99]
I'm trying to get pirate-get to save the magnet URI to the clipboard by using `openCommand` without success.

This is what I have in my config file:

    openCommand = echo '%s' | pbcopy

For reasons unknown to me, the shell is considering everything after `echo` as an argument to it, so it just outputs the magnet URI, the pipe and the `pbcopy` command. Is there some escaping or quoting I need to do? I tried fiddling around a bit with backslashes and quotes without luck.

Any help is appreciated.

**Comment by rnhmjoj** [comment]
It's intentionally done this way. You don't have a full shell because that would make you vulnerable to code execution.  See issues #49 #46.
You could write a function or a shell script to call pbcopy with the pipe.

**Comment by mrzool** [comment]
It's probably me, but I fail to see the security risk in this case. Vulnerable to commands I write myself in my config file?

Thanks for the suggestion, I'll go down the script road.

Closing the issue since this seems to be the expected behavior.

**Comment by rnhmjoj** [comment]
The magnet URI is provided by a more or less random pirate bay mirror. It can possibly contain executable code that would be run when with you command if not properly escaped.

**Comment by mrzool** [comment]
Oh I see, that makes total sense. But wouldn't that be easily addressed by hard-quoting the URI so that the shell treats it as string? Not so simple?

**Comment by rnhmjoj** [comment]
It's actually rather complicated: see quoting in [PHP](http://security.stackexchange.com/questions/3611) for example. I have found out there is this (recently added) [function](https://docs.python.org/3/library/shlex.html#shlex.quote) in the stdlib we could probably use.
Anyway, I don't have much time now: I'll into this nex week probably.
